class ContentWriterAgent:
    """Content Writer Agent — uses the MAAI Blog Production SOP to generate unique content.

    Every section is generated by the LLM with full context about the
    keyword, intent, tone, and specific heading; Python owns the template
    and metadata (see agents/blog_automation.py).
    """

    def run(self, brief):
        from agents.blog_automation import generate_blog_draft

        keyword = brief.get("keyword", "")
        tone = brief.get("tone", "professional")
        word_count = brief.get("word_count_target", 1500)

        draft = generate_blog_draft(
            keyword=keyword,
            title=brief.get("recommended_h1", ""),
            audience=brief.get("target_audience", ""),
            tone=tone,
            word_count=word_count,
        )

        draft["status"] = "Draft Generated"
        return draft
